version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api
    container_name: api
    restart: unless-stopped
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: db
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"